# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-24 21:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('due_date', models.DateTimeField()),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('GP', 'Group project'), ('DP', 'Discussion post'), ('PP', 'Paper'), ('LB', 'Lab')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('section', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('location', models.CharField(max_length=200)),
                ('recurs', models.CharField(choices=[('W', 'Weekly'), ('M', 'Monthly'), ('B', 'Bi-weekly')], max_length=1)),
                ('assoc_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homebase.Course')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.EmailField(max_length=254)),
                ('password_sha1', models.BinaryField(max_length=20)),
                ('pic_url', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='assoc_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homebase.Course'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='assoc_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homebase.User'),
        ),
    ]
