# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-31 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='Richard Stallman', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='type',
            field=models.CharField(choices=[('GP', 'Group project'), ('LB', 'Lab'), ('DP', 'Discussion post'), ('PP', 'Paper')], max_length=2),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='recurs',
            field=models.CharField(choices=[('B', 'Bi-weekly'), ('W', 'Weekly'), ('M', 'Monthly')], max_length=1),
        ),
    ]
