# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-01 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebase', '0002_auto_20160531_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='thing@t.com', max_length=254, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='type',
            field=models.CharField(choices=[('PP', 'Paper'), ('DP', 'Discussion post'), ('GP', 'Group project'), ('LB', 'Lab')], max_length=2),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='recurs',
            field=models.CharField(choices=[('M', 'Monthly'), ('W', 'Weekly'), ('B', 'Bi-weekly')], max_length=1),
        ),
    ]
