# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-01 19:11
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebase', '0003_auto_20160601_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='type',
            field=models.CharField(choices=[('PP', 'Paper'), ('LB', 'Lab'), ('GP', 'Group project'), ('DP', 'Discussion post')], max_length=2),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='recurs',
            field=models.CharField(choices=[('B', 'Bi-weekly'), ('M', 'Monthly'), ('W', 'Weekly')], max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=200, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.EmailValidator]),
        ),
    ]
