# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-01 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebase', '0004_auto_20160601_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='type',
            field=models.CharField(choices=[('GP', 'Group project'), ('LB', 'Lab'), ('DP', 'Discussion post'), ('PP', 'Paper')], max_length=2),
        ),
    ]
