# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-02 05:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homebase', '0007_auto_20160602_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='parent_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homebase.Assignment'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='type',
            field=models.CharField(choices=[('LB', 'Lab'), ('GP', 'Group project'), ('DP', 'Discussion post'), ('PP', 'Paper')], max_length=2),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='recurs',
            field=models.CharField(choices=[('B', 'Bi-weekly'), ('W', 'Weekly'), ('M', 'Monthly')], max_length=1),
        ),
    ]
