# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-02 05:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homebase', '0008_auto_20160602_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homebase.Assignment'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='recurs',
            field=models.CharField(choices=[('M', 'Monthly'), ('B', 'Bi-weekly'), ('W', 'Weekly')], max_length=1),
        ),
    ]
