# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-02 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebase', '0009_auto_20160602_0503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='type',
            field=models.CharField(choices=[('LB', 'Lab'), ('DP', 'Discussion post'), ('PP', 'Paper'), ('GP', 'Group project')], max_length=2),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='recurs',
            field=models.CharField(choices=[('B', 'Bi-weekly'), ('W', 'Weekly'), ('M', 'Monthly')], max_length=1),
        ),
    ]
