# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-02 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebase', '0010_auto_20160602_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='type',
            field=models.CharField(choices=[('PP', 'Paper'), ('DP', 'Discussion post'), ('LB', 'Lab'), ('GP', 'Group project')], max_length=2),
        ),
    ]
