# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-02 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebase', '0011_auto_20160602_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='type',
            field=models.CharField(choices=[('GP', 'Group project'), ('DP', 'Discussion post'), ('PP', 'Paper'), ('LB', 'Lab')], max_length=2),
        ),
    ]
